language: cpp
compiler: gcc
before_install:
  - sudo apt-get install libboost-test-dev -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-7 g++-7 -y
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 999 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --auto gcc
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T bulk-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucamelot58:$BINTRAY_API_KEY "https://api.bintray.com/content/camelot58/OTUS.Cpp/bulk/$TRAVIS_BUILD_NUMBER/bulk-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
